### ISSUE TITLE
wrong file reference on not existing drive

### ISSUE THREAD

**Issue by Stingra-VI** [microsoft/AttackSurfaceAnalyzer#251]
**Describe the bug**
running a report on a not existing directory shows a wrong drive reference.

I would like to point out that this is my first MS "bug" report. If I forget more details, please get back to me.

**To Reproduce**
1. run a compare on two existing reports (before / and after), point it to a not existing directory (kinda forgot to create that before)
2. in the error-message you will see some references to "**D:\a\1\s\Cli\Program.CS**" (Screenshot #1) -  whereas we do not have that drive conntected or started. (see Screenshot#2)

**Expected behavior**
- not that error message. More likely "just the first line, where it states that the path was not found"

**Screenshots**
2 attached

**System Configuration (please complete the following information):**
 - OS Version:  Windows 10, 1709
 - Application Version: AsaCli-win10-2.0.154
 - CLI or GUI:    CLI

**Additional Context**
after creating that directory the command works as expected

![ASA-Burg02](https://user-images.githubusercontent.com/47983116/62209340-9dc7dc80-b399-11e9-9e12-e84980b9ecdb.png)
![ASA-Bug01](https://user-images.githubusercontent.com/47983116/62209341-9e607300-b399-11e9-90ce-594327a2eaa5.jpg)

**Comment by scovetta** [comment]
Thanks for the report, @Stingra-VI!

For the the `D:\a\1\s\Cli\Program.cs` location: I'm pretty sure this path is an artifact of the ASA binary being build in Azure DevOps, which uses that directory structure on its hosted build agents. 

The exception looks like it's trying to access `C:\swrollout\Admin\ASA\…` but isn't finding a that directory. Which is strange, since you're in that directory on the command line. I noticed that the case is different (swrollout vs. SwRollout), which might account for it, but we'll take a deeper look!

**Comment by gfs** [comment]
Thank you for the report @Stingra-VI.  I'm able to reproduce this behavior.  I'll post a fix by the end of the week that will error out before running the full comparisons if the path doesn't exist.

Is having the path automatically created an important feature for you?  It is something I can investigate but is more difficult because ASA runs as Admin/Root and it is obviously undesirable to create an admin owned directory.

**Comment by gfs** [comment]
Fix pushed.  Thanks again for your report @Stingra-VI.

<img width="1375" alt="Screen Shot 2019-08-12 at 11 38 10 PM" src="https://user-images.githubusercontent.com/98900/62920329-4c84f900-bd5a-11e9-9d33-bc34f425417b.png">

**Comment by Stingra-VI** [comment]
Dear Gabe,

Thank you so much for his quick fix and keeping me up to date.

We are just starting with ASA, so it is highly appreciated :)

Best regards

Markus



Am 13. August 2019 08:39:14 MESZ schrieb Gabe Stocco <notifications@github.com>:
>Fix pushed.  Thanks again for your report @Stingra-VI.
>
><img width="1375" alt="Screen Shot 2019-08-12 at 11 38 10 PM"
>src="https://user-images.githubusercontent.com/98900/62920329-4c84f900-bd5a-11e9-9d33-bc34f425417b.png">
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/microsoft/AttackSurfaceAnalyzer/issues/251#issuecomment-520708981

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
