### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by EBlasco-ST** [microsoft/AttackSurfaceAnalyzer#309]
I'm so sorry if this message doesn't goes here... I'm new :S...

I'm trying to download and install this program (Attack Simulator Analyzer 2.0), but i'm don't see the executable file "asa.exe" and i dont see the folder "res" neither.

When i download the project i receipt the folder with files and subfolders, but "res" folder or "asa.exe" file are not here. I don't know if this project needs to be compiled. If i execute a file "AsaLaunch.bat" or "AsaLaunchGUI.bat" doesn't run and i don't receive any message. 

Need help. Can you help me please?

I insist, i'm new and i don't know if this message goes here... I'm so sorry again...

Thanks!

**Comment by gfs** [comment]
Hi Elblasco,

Can you clarify which package you downloaded?

Thanks!

-------- Original Message --------

On Nov 5, 2019, 6:21 PM, EBlasco-ST < notifications@github.com> wrote:

I'm so sorry if this message doesn't goes here... I'm new :S...

I'm trying to download and install this program (Attack Simulator Analyzer 2.0), but i'm don't see the executable file "asa.exe" and i dont see the folder "res" neither.

When i download the project i receipt the folder with files and subfolders, but "res" folder or "asa.exe" file are not here. I don't know if this project needs to be compiled. If i execute a file "AsaLaunch.bat" or "AsaLaunchGUI.bat" doesn't run and i don't receive any message.

Need help. Can you help me please?

I insist, i'm new and i don't know if this message goes here... I'm so sorry again...

Thanks!

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.￼

[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "[https://github.com](<a href=)/microsoft/AttackSurfaceAnalyzer/issues/309?email_source=notifications">https://github.com/microsoft/AttackSurfaceAnalyzer/issues/309?email_source=notifications\u0026email_token=AAAYEVEGD65PKEHDBNX352LQSE3K3A5CNFSM4JI74MR2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HW2VFPQ", "url": "[https://github.com](<a href=)/microsoft/AttackSurfaceAnalyzer/issues/309?email_source=notifications">https://github.com/microsoft/AttackSurfaceAnalyzer/issues/309?email_source=notifications\u0026email_token=AAAYEVEGD65PKEHDBNX352LQSE3K3A5CNFSM4JI74MR2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HW2VFPQ", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by EBlasco-ST** [comment]
Hi Gabe!

Yeah! I have downloaded the package: "AttackSurfaceAnalyzer-master". I don't see anymore... I tried to change the branch and i select the "release/v2.0" or "release/v2.1" too. But with 3 diferents packages i don't see any executable file.

Have i selected the wrong package?

Thanks to you!

**Comment by gfs** [comment]
I think you may be grabbing the code directly rather than a release. You can grab the latest release for your platform from here:

https://github.com/Microsoft/AttackSurfaceAnalyzer/releases/latest

And then running the AsaLaunch (or AsaLaunchGui) depending on package should work. Let me know if you encounter any other issues.

-------- Original Message --------

**Comment by EBlasco-ST** [comment]
Great!

The package are running in my PC! I don't see the page with the link to package download. 

When i running "AsaLaunchGUI", the terminal CMD opens and i check correctly the application.

Thanks for all!
