### ISSUE TITLE
ServiceCollector Failing

### ISSUE THREAD

**Issue by a-gazin** [microsoft/AttackSurfaceAnalyzer#459]
**Describe the bug**
When running the ServiceCollector on Windows 8, Windows Server 2012, (maybe more, but not Win10) 

**To Reproduce**
1. Run `Asa.exe collect -s --verbose`
2. Observe (almost) every object has an error

**Expected behavior**
Not have an error for every service (it seems that is fails for every service)

**Screenshots**
Muted Areas (not the Command line part) are the name of the machine
![Capture_Service](https://user-images.githubusercontent.com/61299470/82618063-d33af200-9b86-11ea-9f45-53646643348e.PNG)

**System Configuration (please complete the following information):**
 - OS: Windows
 - OS Version:  Windows 8.1 x64, Windows Server 2012, could be more. (not Win10)
 - Application Version: 2.2.40+0f97498320
 - CLI or GUI: CLI

**Comment by gfs** [comment]
Thanks for all your reports @a-gazin and for your patience.

I've identified the issue here.  

We're pulling out all the fields in the WMI objects (based on Windows 10 documentation), without a try around each property fetch.  It looks like (at least) one of those properties isn't supported on Windows 8, throwing the error here. (https://github.com/microsoft/AttackSurfaceAnalyzer/blob/244012b9643f326097ea462955772e730a89f8cc/Lib/Collectors/ServiceCollector.cs#L62-L64)  

I have a fix ready in #460 that I'll roll out tonight.

**Comment by a-gazin** [comment]
Thank you for the fix! and also, Thanks for having such a quick response time and also fix time!!
