### ISSUE TITLE
Sandbox: Broken collapse buttons in multiple object types (When initial values are null)

### ISSUE THREAD

**Issue by daalcant** [microsoft/AttackSurfaceAnalyzer#596]
**Description:**
The Sandbox contains broken collapse buttons when viewing the following object types:

- CryptographicKeyObject under "RsaDetails"
- DriverObject under "Signature"
- FileMonitorObject under "FileSystemObject"
- FileSystemObject under "Characteristics"
- FileSystemObject under "MacSignatureStatus"
- FileSystemObject under "SignatureStatus"
- ProcessObject under "MainModule"
- ProcessObject under "Item"
- TpmObject under "Item" (5x)

**Expected behavior:**
The collapse buttons should expand and collapse object details

**To Reproduce:**

1. Run ASA, open GUI
2. Click Sandbox page
3. Select any of the above mentioned types, e.g. DriverObject
4. Create the object
5. Click 'View' tab to view the object, expand its contents
6. Find some broken collapse buttons

**Configuration:**

ASA Application Version: v2.3.146-beta
OAT Application Version: 718b12bddf671984074aefe98e6789c4dd0c7b95

**Comment by gfs** [comment]
That seems to be because the default value for these things is null when the variable is created.  They should all be capable of being represented but there's no mechanism to initialize them.  Unclear what the right approach here would be other than to possibly just silently hide things which are null and have no mechanism for creation?

**Comment by gfs** [comment]
This was fixed in #607
