### ISSUE TITLE
Minimum pre-requisites are not documented

### ISSUE THREAD

**Issue by slaymaker1907** [microsoft/AttackSurfaceAnalyzer#648]
**Describe the bug**
There are a huge number of errors when running in a container due to missing libraries. These should at least be well documented because installing a bunch of stuff before using this tool defeats the very purpose of this tool.

**To Reproduce**
Create a ubuntu:20.04 docker container and download ASA (unzipped) to the container. Try running "Asa --help"

**Expected behavior**
Help should be displayed.

**Screenshots**

**System Configuration (please complete the following information):**
 - OS: ubuntu:20.04 container
 - OS Version: 20.04
 - Application Version: 2.3.277
 - CLI or GUI:CLI

**Additional Context**

**Comment by slaymaker1907** [comment]
Ideally there should be no dependencies whatsoever with these binaries, but they actually require libssl and libicu at the very least.

**Comment by gfs** [comment]
> To Reproduce
> Create a ubuntu:20.04 docker container and download ASA (unzipped) to the container. Try running "Asa --help"

I can't reproduce this in a regular Ubuntu 20.04 VM.  Earlier versions of Asa did use iproute2 but I just ran a port collector on linux without issue and it looks like I call `ss` now instead which is included. 

<img width="600" alt="image" src="https://user-images.githubusercontent.com/98900/161168701-40cdbe75-494c-4b29-b083-a38b84fec7d0.png">

> There are a huge number of errors when running in a container due to missing libraries.
>  but they actually require libssl and libicu at the very least

These appear to actually be underlying requirements for any .NET application to run on your image - not Attack Surface Analyzer dependencies.

https://github.com/dotnet/core/blob/main/release-notes/6.0/linux-packages.md

Instead of downloading from GitHub releases you could create your image using this base:
https://hub.docker.com/_/microsoft-dotnet-sdk/

And then add `RUN dotnet tool install -g Microsoft.CST.AttackSurfaceAnalyzer.CLI` to your dockerfile.

You will then be able to `asa` globally in your docker image.

> because installing a bunch of stuff before using this tool defeats the very purpose of this tool.

ASA analysis generates a diff so it should not make much net difference if you have more/less initially - other than that collection speed scales with amount of data to collect.  Anything baked into the image before ASA runs will be there unaltered in both the first and second collection so they should cancel out.

**Comment by gfs** [comment]
I've added a note to the documentation about the linux requirements for .NET, and the recommendation to use the .NET docker image.
