### ISSUE TITLE
Some CertificateObjects get created with null store locations

### ISSUE THREAD

**Issue by Guydalf** [Microsoft/AttackSurfaceAnalyzer#80]
![ExceptionOnTelmetryPost](https://user-images.githubusercontent.com/47648296/55659162-52b80700-57b5-11e9-968b-2075c01456c5.png)
**Describe the bug**
Detected an exception being reported regularly for GUI version of app related to inability to write to certificate table.

**To Reproduce**
1. Go to Scan, run a couple
2. Click on Results to analyze
3. Note captured exception being sent as part of telemetry

**Expected behavior**
No exceptions reported on normal application use

**Screenshots**

**System Configuration (please complete the following information):**
 - OS: [e.g. Windows]
 - OS Version: [e.g. Windows 10 1803]
 - Application Version: [e.g. 2.0.1-beta+50af283871]
 - CLI or GUI:

**Additional Context**
![ExceptionOnTelmetryPost](https://user-images.githubusercontent.com/47648296/55659170-5d729c00-57b5-11e9-8c61-78bcfadc7b55.png)

**Comment by gfs** [comment]
Should investigate why this is happening.  The underlying code is deserializing a CertificateObject, which otherwise should be working fine, so it likely means that either a certificate object was created with a null StoreLocation field, or somehow there's a ghost null result when there are otherwise no results.

**Comment by gfs** [comment]
Fixed in #116.
